version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: mohllal/reverseproxy
  backend_user:
    build:
      context: ../../udacity-c3-restapi-user
    image: mohllal/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-c3-restapi-feed  
    image: mohllal/udacity-restapi-feed
  backend_filter:
    build:
      context: ../../udacity-c3-image-filter
    image: mohllal/udacity-image-filter
  frontend:
    build:
      context: ../../udacity-c3-frontend
      args:
        - BUILD_ENV=production
    image: mohllal/udacity-frontend
